services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  mysql-db:
  redis-data:
